package com.cgaf.model;

// Generated 05-ago-2015 22:35:05 by Hibernate Tools 3.4.0.CR1



/**
 * CtAcumulado generated by hbm2java
 */
public class CtAcumulado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idAcumulado;
	private CtTipoAcumulado ctTipoAcumulado;
	private String descAcumulado;

	public CtAcumulado() {
	}

	public CtAcumulado(Integer idAcumulado, CtTipoAcumulado ctTipoAcumulado) {
		this.idAcumulado = idAcumulado;
		this.ctTipoAcumulado = ctTipoAcumulado;
	}

	public CtAcumulado(Integer idAcumulado, CtTipoAcumulado ctTipoAcumulado,
			String descAcumulado) {
		this.idAcumulado = idAcumulado;
		this.ctTipoAcumulado = ctTipoAcumulado;
		this.descAcumulado = descAcumulado;
	}

	public Integer getIdAcumulado() {
		return this.idAcumulado;
	}

	public void setIdAcumulado(Integer idAcumulado) {
		this.idAcumulado = idAcumulado;
	}

	public CtTipoAcumulado getCtTipoAcumulado() {
		return this.ctTipoAcumulado;
	}

	public void setCtTipoAcumulado(CtTipoAcumulado ctTipoAcumulado) {
		this.ctTipoAcumulado = ctTipoAcumulado;
	}

	public String getDescAcumulado() {
		return this.descAcumulado;
	}

	public void setDescAcumulado(String descAcumulado) {
		this.descAcumulado = descAcumulado;
	}

}
