package com.cgaf.model;

// Generated 05-ago-2015 22:35:05 by Hibernate Tools 3.4.0.CR1



/**
 * CtAcumulado generated by hbm2java
 */
public class CtAcumulado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idAcumulado;
	private CtTipoAcumulado ctTipoAcumulado;
	private String descAcumulado;
	private String funcionAcumulado;
	private String formatoAgrupacionAcumulado;

	public CtAcumulado() {
	}

	public CtAcumulado(Integer idAcumulado, CtTipoAcumulado ctTipoAcumulado) {
		this.idAcumulado = idAcumulado;
		this.ctTipoAcumulado = ctTipoAcumulado;
	}

	public CtAcumulado(Integer idAcumulado, CtTipoAcumulado ctTipoAcumulado, String descAcumulado,
			String funcionAcumulado, String formatoAgrupacionAcumulado) {
		super();
		this.idAcumulado = idAcumulado;
		this.ctTipoAcumulado = ctTipoAcumulado;
		this.descAcumulado = descAcumulado;
		this.funcionAcumulado = funcionAcumulado;
		this.formatoAgrupacionAcumulado = formatoAgrupacionAcumulado;
	}

	public Integer getIdAcumulado() {
		return idAcumulado;
	}

	public void setIdAcumulado(Integer idAcumulado) {
		this.idAcumulado = idAcumulado;
	}

	public CtTipoAcumulado getCtTipoAcumulado() {
		return ctTipoAcumulado;
	}

	public void setCtTipoAcumulado(CtTipoAcumulado ctTipoAcumulado) {
		this.ctTipoAcumulado = ctTipoAcumulado;
	}

	public String getDescAcumulado() {
		return descAcumulado;
	}

	public void setDescAcumulado(String descAcumulado) {
		this.descAcumulado = descAcumulado;
	}

	public String getFuncionAcumulado() {
		return funcionAcumulado;
	}

	public void setFuncionAcumulado(String funcionAcumulado) {
		this.funcionAcumulado = funcionAcumulado;
	}

	public String getFormatoAgrupacionAcumulado() {
		return formatoAgrupacionAcumulado;
	}

	public void setFormatoAgrupacionAcumulado(String formatoAgrupacionAcumulado) {
		this.formatoAgrupacionAcumulado = formatoAgrupacionAcumulado;
	}
}
