package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

/**
 * CtConcepto generated by hbm2java
 */
public class CtConcepto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idPee;
	private CtVariable ctVariable;
	private CtTabla ctTabla;

	public CtConcepto() {
	}

	public CtConcepto(short idPee, CtVariable ctVariable, CtTabla ctTabla) {
		this.idPee = idPee;
		this.ctVariable = ctVariable;
		this.ctTabla = ctTabla;
	}

	public short getIdPee() {
		return this.idPee;
	}

	public void setIdPee(short idPee) {
		this.idPee = idPee;
	}

	public CtVariable getCtVariable() {
		return this.ctVariable;
	}

	public void setCtVariable(CtVariable ctVariable) {
		this.ctVariable = ctVariable;
	}

	public CtTabla getCtTabla() {
		return this.ctTabla;
	}

	public void setCtTabla(CtTabla ctTabla) {
		this.ctTabla = ctTabla;
	}

}
