package com.cgaf.model;

// Generated 05-ago-2015 22:35:05 by Hibernate Tools 3.4.0.CR1


/**
 * CtConcepto generated by hbm2java
 */
public class CtConcepto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSecuencial;
	private CtVariable ctVariable;
	private CtProductores ctProductores;
	private CtTabla ctTabla;

	public CtConcepto() {
	}

	public CtConcepto(Integer idSecuencial, CtVariable ctVariable,
			CtProductores ctProductores, CtTabla ctTabla) {
		this.idSecuencial = idSecuencial;
		this.ctVariable = ctVariable;
		this.ctProductores = ctProductores;
		this.ctTabla = ctTabla;
	}

	public Integer getIdSecuencial() {
		return this.idSecuencial;
	}

	public void setIdSecuencial(Integer idSecuencial) {
		this.idSecuencial = idSecuencial;
	}

	public CtVariable getCtVariable() {
		return this.ctVariable;
	}

	public void setCtVariable(CtVariable ctVariable) {
		this.ctVariable = ctVariable;
	}

	public CtProductores getCtProductores() {
		return this.ctProductores;
	}

	public void setCtProductores(CtProductores ctProductores) {
		this.ctProductores = ctProductores;
	}

	public CtTabla getCtTabla() {
		return this.ctTabla;
	}

	public void setCtTabla(CtTabla ctTabla) {
		this.ctTabla = ctTabla;
	}

}
