package com.cgaf.model;

// Generated 04-ago-2015 22:38:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CtProductores generated by hbm2java
 */
public class CtProductores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPee;
	private String descPee;
	private Set<HtCincenergiaRespaldo> htCincenergiaRespaldos = new HashSet<HtCincenergiaRespaldo>(
			0);
	private Set<HtCinccromatografo> htCinccromatografos = new HashSet<HtCinccromatografo>(
			0);
	private Set<HtCincestsuper> htCincestsupers = new HashSet<HtCincestsuper>(0);
	private Set<HtCincenergia> htCincenergias = new HashSet<HtCincenergia>(0);
	private Set<HtCincderivada> htCincderivadas = new HashSet<HtCincderivada>(0);
	private Set<HtCincambiental> htCincambientals = new HashSet<HtCincambiental>(
			0);

	public CtProductores() {
	}

	public CtProductores(Integer idPee) {
		this.idPee = idPee;
	}

	public CtProductores(Integer idPee, String descPee,
			Set<HtCincenergiaRespaldo> htCincenergiaRespaldos,
			Set<HtCinccromatografo> htCinccromatografos,
			Set<HtCincestsuper> htCincestsupers,
			Set<HtCincenergia> htCincenergias,
			Set<HtCincderivada> htCincderivadas,
			Set<HtCincambiental> htCincambientals) {
		this.idPee = idPee;
		this.descPee = descPee;
		this.htCincenergiaRespaldos = htCincenergiaRespaldos;
		this.htCinccromatografos = htCinccromatografos;
		this.htCincestsupers = htCincestsupers;
		this.htCincenergias = htCincenergias;
		this.htCincderivadas = htCincderivadas;
		this.htCincambientals = htCincambientals;
	}

	public Integer getIdPee() {
		return this.idPee;
	}

	public void setIdPee(Integer idPee) {
		this.idPee = idPee;
	}

	public String getDescPee() {
		return this.descPee;
	}

	public void setDescPee(String descPee) {
		this.descPee = descPee;
	}

	public Set<HtCincenergiaRespaldo> getHtCincenergiaRespaldos() {
		return this.htCincenergiaRespaldos;
	}

	public void setHtCincenergiaRespaldos(
			Set<HtCincenergiaRespaldo> htCincenergiaRespaldos) {
		this.htCincenergiaRespaldos = htCincenergiaRespaldos;
	}

	public Set<HtCinccromatografo> getHtCinccromatografos() {
		return this.htCinccromatografos;
	}

	public void setHtCinccromatografos(
			Set<HtCinccromatografo> htCinccromatografos) {
		this.htCinccromatografos = htCinccromatografos;
	}

	public Set<HtCincestsuper> getHtCincestsupers() {
		return this.htCincestsupers;
	}

	public void setHtCincestsupers(Set<HtCincestsuper> htCincestsupers) {
		this.htCincestsupers = htCincestsupers;
	}

	public Set<HtCincenergia> getHtCincenergias() {
		return this.htCincenergias;
	}

	public void setHtCincenergias(Set<HtCincenergia> htCincenergias) {
		this.htCincenergias = htCincenergias;
	}

	public Set<HtCincderivada> getHtCincderivadas() {
		return this.htCincderivadas;
	}

	public void setHtCincderivadas(Set<HtCincderivada> htCincderivadas) {
		this.htCincderivadas = htCincderivadas;
	}

	public Set<HtCincambiental> getHtCincambientals() {
		return this.htCincambientals;
	}

	public void setHtCincambientals(Set<HtCincambiental> htCincambientals) {
		this.htCincambientals = htCincambientals;
	}

}
