package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CtRoles generated by hbm2java
 */
public class CtRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idRol;
	private String descripcionRol;
	private Serializable fechaAlta;
	private Serializable fechaUltmod;
	private String ultimoUsuario;
	private boolean activo;
	private Set<CtUsuarios> ctUsuarioses = new HashSet<CtUsuarios>(0);

	public CtRoles() {
	}

	public CtRoles(BigDecimal idRol, String descripcionRol,
			Serializable fechaAlta, boolean activo) {
		this.idRol = idRol;
		this.descripcionRol = descripcionRol;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
	}

	public CtRoles(BigDecimal idRol, String descripcionRol,
			Serializable fechaAlta, Serializable fechaUltmod,
			String ultimoUsuario, boolean activo, Set<CtUsuarios> ctUsuarioses) {
		this.idRol = idRol;
		this.descripcionRol = descripcionRol;
		this.fechaAlta = fechaAlta;
		this.fechaUltmod = fechaUltmod;
		this.ultimoUsuario = ultimoUsuario;
		this.activo = activo;
		this.ctUsuarioses = ctUsuarioses;
	}

	public BigDecimal getIdRol() {
		return this.idRol;
	}

	public void setIdRol(BigDecimal idRol) {
		this.idRol = idRol;
	}

	public String getDescripcionRol() {
		return this.descripcionRol;
	}

	public void setDescripcionRol(String descripcionRol) {
		this.descripcionRol = descripcionRol;
	}

	public Serializable getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Serializable fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Serializable getFechaUltmod() {
		return this.fechaUltmod;
	}

	public void setFechaUltmod(Serializable fechaUltmod) {
		this.fechaUltmod = fechaUltmod;
	}

	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<CtUsuarios> getCtUsuarioses() {
		return this.ctUsuarioses;
	}

	public void setCtUsuarioses(Set<CtUsuarios> ctUsuarioses) {
		this.ctUsuarioses = ctUsuarioses;
	}

}
