package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CtTabla generated by hbm2java
 */
public class CtTabla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTabla;
	private String descTabla;
	private Set<CtConcepto> ctConceptos = new HashSet<CtConcepto>(0);

	public CtTabla() {
	}

	public CtTabla(Integer idTabla, String descTabla) {
		this.idTabla = idTabla;
		this.descTabla = descTabla;
	}

	public CtTabla(Integer idTabla, String descTabla, Set<CtConcepto> ctConceptos) {
		this.idTabla = idTabla;
		this.descTabla = descTabla;
		this.ctConceptos = ctConceptos;
	}

	public Integer getIdTabla() {
		return this.idTabla;
	}

	public void setIdTabla(Integer idTabla) {
		this.idTabla = idTabla;
	}

	public String getDescTabla() {
		return this.descTabla;
	}

	public void setDescTabla(String descTabla) {
		this.descTabla = descTabla;
	}

	public Set<CtConcepto> getCtConceptos() {
		return this.ctConceptos;
	}

	public void setCtConceptos(Set<CtConcepto> ctConceptos) {
		this.ctConceptos = ctConceptos;
	}

}
