package com.cgaf.model;

// Generated 04-ago-2015 22:38:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CtTipoVariable generated by hbm2java
 */
public class CtTipoVariable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTipoVariable;
	private String descTipoVariable;
	private Set<CtVariable> ctVariable = new HashSet<CtVariable>(0);

	public CtTipoVariable() {
	}

	public CtTipoVariable(Integer idTipoVariable, String descTipoVariable) {
		this.idTipoVariable = idTipoVariable;
		this.descTipoVariable = descTipoVariable;
	}

	public CtTipoVariable(Integer idTipoVariable, String descTipoVariable,
			Set<CtVariable> ctVariable) {
		this.idTipoVariable = idTipoVariable;
		this.descTipoVariable = descTipoVariable;
		this.ctVariable = ctVariable;
	}

	public Integer getIdTipoVariable() {
		return this.idTipoVariable;
	}

	public void setIdTipoVariable(Integer idTipoVariable) {
		this.idTipoVariable = idTipoVariable;
	}

	public String getDescTipoVariable() {
		return this.descTipoVariable;
	}

	public void setDescTipoVariable(String descTipoVariable) {
		this.descTipoVariable = descTipoVariable;
	}

	public Set<CtVariable> getCtVariable() {
		return this.ctVariable;
	}

	public void setCtVariable(Set<CtVariable> ctVariable) {
		this.ctVariable = ctVariable;
	}

}
