package com.cgaf.model;

// Generated 05-ago-2015 22:35:05 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CtTipoAcumulado generated by hbm2java
 */
public class CtTipoAcumulado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTipoAcumulado;
	private String descTipoAcumulado;
	private Set<CtAcumulado> ctAcumulado = new HashSet<CtAcumulado>(0);

	public CtTipoAcumulado() {
	}

	public CtTipoAcumulado(Integer idTipoAcumulado) {
		this.idTipoAcumulado = idTipoAcumulado;
	}

	public CtTipoAcumulado(Integer idTipoAcumulado,
			String descTipoAcumulado, Set<CtAcumulado> ctAcumulado) {
		this.idTipoAcumulado = idTipoAcumulado;
		this.descTipoAcumulado = descTipoAcumulado;
		this.ctAcumulado = ctAcumulado;
	}

	public Integer getIdTipoAcumulado() {
		return this.idTipoAcumulado;
	}

	public void setIdTipoAcumulado(Integer idTipoAcumulado) {
		this.idTipoAcumulado = idTipoAcumulado;
	}

	public String getDescTipoAcumulado() {
		return this.descTipoAcumulado;
	}

	public void setDescTipoAcumulado(String descTipoAcumulado) {
		this.descTipoAcumulado = descTipoAcumulado;
	}

	public Set<CtAcumulado> getCtAcumulado() {
		return this.ctAcumulado;
	}

	public void setCtAcumulado(Set<CtAcumulado> ctAcumulado) {
		this.ctAcumulado = ctAcumulado;
	}

}
