package com.cgaf.model;

// Generated 04-ago-2015 22:38:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CtVariable generated by hbm2java
 */
public class CtVariable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idVariable;
	private CtTipoVariable ctTipoVariable;
	private String descVariable;
	private String descUnidad;
	private String descNemonico;
	private String descVariableR;
	private Set<HtCinccromatografo> htCinccromatografos = new HashSet<HtCinccromatografo>(
			0);
	private Set<HtCincestsuper> htCincestsupers = new HashSet<HtCincestsuper>(0);
	private Set<HtCincenergia> htCincenergias = new HashSet<HtCincenergia>(0);
	private Set<HtCincderivada> htCincderivadas = new HashSet<HtCincderivada>(0);
	private Set<HtCincambiental> htCincambientals = new HashSet<HtCincambiental>(
			0);
	private Set<CtConcepto> ctConceptos = new HashSet<CtConcepto>(0);
	private Set<HtCincenergiaRespaldo> htCincenergiaRespaldos = new HashSet<HtCincenergiaRespaldo>(
			0);

	public CtVariable() {
	}

	public CtVariable(Integer idVariable, String descVariable) {
		this.idVariable = idVariable;
		this.descVariable = descVariable;
	}

	public CtVariable(Integer idVariable, CtTipoVariable ctTipoVariable,
			String descVariable, String descUnidad, String descNemonico,
			String descVariableR, Set<HtCinccromatografo> htCinccromatografos,
			Set<HtCincestsuper> htCincestsupers,
			Set<HtCincenergia> htCincenergias,
			Set<HtCincderivada> htCincderivadas,
			Set<HtCincambiental> htCincambientals, Set<CtConcepto> ctConceptos,
			Set<HtCincenergiaRespaldo> htCincenergiaRespaldos) {
		this.idVariable = idVariable;
		this.ctTipoVariable = ctTipoVariable;
		this.descVariable = descVariable;
		this.descUnidad = descUnidad;
		this.descNemonico = descNemonico;
		this.descVariableR = descVariableR;
		this.htCinccromatografos = htCinccromatografos;
		this.htCincestsupers = htCincestsupers;
		this.htCincenergias = htCincenergias;
		this.htCincderivadas = htCincderivadas;
		this.htCincambientals = htCincambientals;
		this.ctConceptos = ctConceptos;
		this.htCincenergiaRespaldos = htCincenergiaRespaldos;
	}

	public Integer getIdVariable() {
		return this.idVariable;
	}

	public void setIdVariable(Integer idVariable) {
		this.idVariable = idVariable;
	}

	public CtTipoVariable getCtTipoVariable() {
		return this.ctTipoVariable;
	}

	public void setCtTipoVariable(CtTipoVariable ctTipoVariable) {
		this.ctTipoVariable = ctTipoVariable;
	}

	public String getDescVariable() {
		return this.descVariable;
	}

	public void setDescVariable(String descVariable) {
		this.descVariable = descVariable;
	}

	public String getDescUnidad() {
		return this.descUnidad;
	}

	public void setDescUnidad(String descUnidad) {
		this.descUnidad = descUnidad;
	}

	public String getDescNemonico() {
		return this.descNemonico;
	}

	public void setDescNemonico(String descNemonico) {
		this.descNemonico = descNemonico;
	}

	public String getDescVariableR() {
		return this.descVariableR;
	}

	public void setDescVariableR(String descVariableR) {
		this.descVariableR = descVariableR;
	}

	public Set<HtCinccromatografo> getHtCinccromatografos() {
		return this.htCinccromatografos;
	}

	public void setHtCinccromatografos(
			Set<HtCinccromatografo> htCinccromatografos) {
		this.htCinccromatografos = htCinccromatografos;
	}

	public Set<HtCincestsuper> getHtCincestsupers() {
		return this.htCincestsupers;
	}

	public void setHtCincestsupers(Set<HtCincestsuper> htCincestsupers) {
		this.htCincestsupers = htCincestsupers;
	}

	public Set<HtCincenergia> getHtCincenergias() {
		return this.htCincenergias;
	}

	public void setHtCincenergias(Set<HtCincenergia> htCincenergias) {
		this.htCincenergias = htCincenergias;
	}

	public Set<HtCincderivada> getHtCincderivadas() {
		return this.htCincderivadas;
	}

	public void setHtCincderivadas(Set<HtCincderivada> htCincderivadas) {
		this.htCincderivadas = htCincderivadas;
	}

	public Set<HtCincambiental> getHtCincambientals() {
		return this.htCincambientals;
	}

	public void setHtCincambientals(Set<HtCincambiental> htCincambientals) {
		this.htCincambientals = htCincambientals;
	}

	public Set<CtConcepto> getCtConceptos() {
		return this.ctConceptos;
	}

	public void setCtConceptos(Set<CtConcepto> ctConceptos) {
		this.ctConceptos = ctConceptos;
	}

	public Set<HtCincenergiaRespaldo> getHtCincenergiaRespaldos() {
		return this.htCincenergiaRespaldos;
	}

	public void setHtCincenergiaRespaldos(
			Set<HtCincenergiaRespaldo> htCincenergiaRespaldos) {
		this.htCincenergiaRespaldos = htCincenergiaRespaldos;
	}

}
