package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Blob;

/**
 * DHashes generated by hbm2java
 */
public class DHashes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idHash;
	private CtUsuarios ctUsuarios;
	private Blob hash;

	public DHashes() {
	}

	public DHashes(BigDecimal idHash, CtUsuarios ctUsuarios, Blob hash) {
		this.idHash = idHash;
		this.ctUsuarios = ctUsuarios;
		this.hash = hash;
	}

	public BigDecimal getIdHash() {
		return this.idHash;
	}

	public void setIdHash(BigDecimal idHash) {
		this.idHash = idHash;
	}

	public CtUsuarios getCtUsuarios() {
		return this.ctUsuarios;
	}

	public void setCtUsuarios(CtUsuarios ctUsuarios) {
		this.ctUsuarios = ctUsuarios;
	}

	public Blob getHash() {
		return this.hash;
	}

	public void setHash(Blob hash) {
		this.hash = hash;
	}

}
