package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

/**
 * DHashes generated by hbm2java
 */
public class DHashes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idHash;
	private CtUsuarios ctUsuarios;
	private String hash;

	public DHashes() {
	}

	public DHashes(Integer idHash, CtUsuarios ctUsuarios, String hash) {
		this.idHash = idHash;
		this.ctUsuarios = ctUsuarios;
		this.hash = hash;
	}

	public Integer getIdHash() {
		return this.idHash;
	}

	public void setIdHash(Integer idHash) {
		this.idHash = idHash;
	}

	public CtUsuarios getCtUsuarios() {
		return this.ctUsuarios;
	}

	public void setCtUsuarios(CtUsuarios ctUsuarios) {
		this.ctUsuarios = ctUsuarios;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}
