package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

/**
 * DtPlantilla generated by hbm2java
 */
public class DtPlantilla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DtPlantillaId id;

	public DtPlantilla() {
	}

	public DtPlantilla(DtPlantillaId id) {
		this.id = id;
	}

	public DtPlantillaId getId() {
		return this.id;
	}

	public void setId(DtPlantillaId id) {
		this.id = id;
	}

}
