package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * DtPlantillaId generated by hbm2java
 */
public class DtPlantillaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idPlantilla;
	private Integer valRen;
	private Integer valCol;
	private String nomCelcol;
	private String valTipo;
	private String valCriterio;
	private Byte valHoja;
	private String tipoDato;
	private String nomHoja;
	private BigDecimal idDtPlantilla;
	private String titulo;

	public DtPlantillaId() {
	}

	public DtPlantillaId(short idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public DtPlantillaId(short idPlantilla, Integer valRen, Integer valCol,
			String nomCelcol, String valTipo, String valCriterio, Byte valHoja,
			String tipoDato, String nomHoja, BigDecimal idDtPlantilla,
			String titulo) {
		this.idPlantilla = idPlantilla;
		this.valRen = valRen;
		this.valCol = valCol;
		this.nomCelcol = nomCelcol;
		this.valTipo = valTipo;
		this.valCriterio = valCriterio;
		this.valHoja = valHoja;
		this.tipoDato = tipoDato;
		this.nomHoja = nomHoja;
		this.idDtPlantilla = idDtPlantilla;
		this.titulo = titulo;
	}

	public short getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(short idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public Integer getValRen() {
		return this.valRen;
	}

	public void setValRen(Integer valRen) {
		this.valRen = valRen;
	}

	public Integer getValCol() {
		return this.valCol;
	}

	public void setValCol(Integer valCol) {
		this.valCol = valCol;
	}

	public String getNomCelcol() {
		return this.nomCelcol;
	}

	public void setNomCelcol(String nomCelcol) {
		this.nomCelcol = nomCelcol;
	}

	public String getValTipo() {
		return this.valTipo;
	}

	public void setValTipo(String valTipo) {
		this.valTipo = valTipo;
	}

	public String getValCriterio() {
		return this.valCriterio;
	}

	public void setValCriterio(String valCriterio) {
		this.valCriterio = valCriterio;
	}

	public Byte getValHoja() {
		return this.valHoja;
	}

	public void setValHoja(Byte valHoja) {
		this.valHoja = valHoja;
	}

	public String getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(String tipoDato) {
		this.tipoDato = tipoDato;
	}

	public String getNomHoja() {
		return this.nomHoja;
	}

	public void setNomHoja(String nomHoja) {
		this.nomHoja = nomHoja;
	}

	public BigDecimal getIdDtPlantilla() {
		return this.idDtPlantilla;
	}

	public void setIdDtPlantilla(BigDecimal idDtPlantilla) {
		this.idDtPlantilla = idDtPlantilla;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DtPlantillaId))
			return false;
		DtPlantillaId castOther = (DtPlantillaId) other;

		return (this.getIdPlantilla() == castOther.getIdPlantilla())
				&& ((this.getValRen() == castOther.getValRen()) || (this
						.getValRen() != null && castOther.getValRen() != null && this
						.getValRen().equals(castOther.getValRen())))
				&& ((this.getValCol() == castOther.getValCol()) || (this
						.getValCol() != null && castOther.getValCol() != null && this
						.getValCol().equals(castOther.getValCol())))
				&& ((this.getNomCelcol() == castOther.getNomCelcol()) || (this
						.getNomCelcol() != null
						&& castOther.getNomCelcol() != null && this
						.getNomCelcol().equals(castOther.getNomCelcol())))
				&& ((this.getValTipo() == castOther.getValTipo()) || (this
						.getValTipo() != null && castOther.getValTipo() != null && this
						.getValTipo().equals(castOther.getValTipo())))
				&& ((this.getValCriterio() == castOther.getValCriterio()) || (this
						.getValCriterio() != null
						&& castOther.getValCriterio() != null && this
						.getValCriterio().equals(castOther.getValCriterio())))
				&& ((this.getValHoja() == castOther.getValHoja()) || (this
						.getValHoja() != null && castOther.getValHoja() != null && this
						.getValHoja().equals(castOther.getValHoja())))
				&& ((this.getTipoDato() == castOther.getTipoDato()) || (this
						.getTipoDato() != null
						&& castOther.getTipoDato() != null && this
						.getTipoDato().equals(castOther.getTipoDato())))
				&& ((this.getNomHoja() == castOther.getNomHoja()) || (this
						.getNomHoja() != null && castOther.getNomHoja() != null && this
						.getNomHoja().equals(castOther.getNomHoja())))
				&& ((this.getIdDtPlantilla() == castOther.getIdDtPlantilla()) || (this
						.getIdDtPlantilla() != null
						&& castOther.getIdDtPlantilla() != null && this
						.getIdDtPlantilla()
						.equals(castOther.getIdDtPlantilla())))
				&& ((this.getTitulo() == castOther.getTitulo()) || (this
						.getTitulo() != null && castOther.getTitulo() != null && this
						.getTitulo().equals(castOther.getTitulo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPlantilla();
		result = 37 * result
				+ (getValRen() == null ? 0 : this.getValRen().hashCode());
		result = 37 * result
				+ (getValCol() == null ? 0 : this.getValCol().hashCode());
		result = 37 * result
				+ (getNomCelcol() == null ? 0 : this.getNomCelcol().hashCode());
		result = 37 * result
				+ (getValTipo() == null ? 0 : this.getValTipo().hashCode());
		result = 37
				* result
				+ (getValCriterio() == null ? 0 : this.getValCriterio()
						.hashCode());
		result = 37 * result
				+ (getValHoja() == null ? 0 : this.getValHoja().hashCode());
		result = 37 * result
				+ (getTipoDato() == null ? 0 : this.getTipoDato().hashCode());
		result = 37 * result
				+ (getNomHoja() == null ? 0 : this.getNomHoja().hashCode());
		result = 37
				* result
				+ (getIdDtPlantilla() == null ? 0 : this.getIdDtPlantilla()
						.hashCode());
		result = 37 * result
				+ (getTitulo() == null ? 0 : this.getTitulo().hashCode());
		return result;
	}

}
