package com.cgaf.model;

// Generated 04-ago-2015 22:38:37 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * HtCincestsuper generated by hbm2java
 */
public class HtCincestsuper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSecuencial;
	private CtVariable ctVariable;
	private CtProductores ctProductores;
	private Timestamp fechPeriodo;
	private Integer numPeriodo;
	private Double valValor;
	private Integer idVersion;
	private Integer idEstatus;

	public HtCincestsuper() {
	}

	public HtCincestsuper(Integer idSecuencial, CtVariable ctVariable,
			CtProductores ctProductores, Timestamp fechPeriodo,
			Integer numPeriodo) {
		this.idSecuencial = idSecuencial;
		this.ctVariable = ctVariable;
		this.ctProductores = ctProductores;
		this.fechPeriodo = fechPeriodo;
		this.numPeriodo = numPeriodo;
	}

	public HtCincestsuper(Integer idSecuencial, CtVariable ctVariable,
			CtProductores ctProductores, Timestamp fechPeriodo,
			Integer numPeriodo, Double valValor, Integer idVersion,
			Integer idEstatus) {
		this.idSecuencial = idSecuencial;
		this.ctVariable = ctVariable;
		this.ctProductores = ctProductores;
		this.fechPeriodo = fechPeriodo;
		this.numPeriodo = numPeriodo;
		this.valValor = valValor;
		this.idVersion = idVersion;
		this.idEstatus = idEstatus;
	}

	public Integer getIdSecuencial() {
		return this.idSecuencial;
	}

	public void setIdSecuencial(Integer idSecuencial) {
		this.idSecuencial = idSecuencial;
	}

	public CtVariable getCtVariable() {
		return this.ctVariable;
	}

	public void setCtVariable(CtVariable ctVariable) {
		this.ctVariable = ctVariable;
	}

	public CtProductores getCtProductores() {
		return this.ctProductores;
	}

	public void setCtProductores(CtProductores ctProductores) {
		this.ctProductores = ctProductores;
	}

	public Timestamp getFechPeriodo() {
		return this.fechPeriodo;
	}

	public void setFechPeriodo(Timestamp fechPeriodo) {
		this.fechPeriodo = fechPeriodo;
	}

	public Integer getNumPeriodo() {
		return this.numPeriodo;
	}

	public void setNumPeriodo(Integer numPeriodo) {
		this.numPeriodo = numPeriodo;
	}

	public Double getValValor() {
		return this.valValor;
	}

	public void setValValor(Double valValor) {
		this.valValor = valValor;
	}

	public Integer getIdVersion() {
		return this.idVersion;
	}

	public void setIdVersion(Integer idVersion) {
		this.idVersion = idVersion;
	}

	public Integer getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(Integer idEstatus) {
		this.idEstatus = idEstatus;
	}

}
