package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * HtCincambiental generated by hbm2java
 */
public class HtCincambiental implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idPee;
	private CtVariable ctVariable;
	private Date fechPeriodo;
	private long numPeriodo;
	private Double valValor;
	private Long idVersion;
	private BigDecimal idEstatus;

	public HtCincambiental() {
	}

	public HtCincambiental(short idPee, CtVariable ctVariable,
			Date fechPeriodo, long numPeriodo) {
		this.idPee = idPee;
		this.ctVariable = ctVariable;
		this.fechPeriodo = fechPeriodo;
		this.numPeriodo = numPeriodo;
	}

	public HtCincambiental(short idPee, CtVariable ctVariable,
			Date fechPeriodo, long numPeriodo, Double valValor, Long idVersion,
			BigDecimal idEstatus) {
		this.idPee = idPee;
		this.ctVariable = ctVariable;
		this.fechPeriodo = fechPeriodo;
		this.numPeriodo = numPeriodo;
		this.valValor = valValor;
		this.idVersion = idVersion;
		this.idEstatus = idEstatus;
	}

	public short getIdPee() {
		return this.idPee;
	}

	public void setIdPee(short idPee) {
		this.idPee = idPee;
	}

	public CtVariable getCtVariable() {
		return this.ctVariable;
	}

	public void setCtVariable(CtVariable ctVariable) {
		this.ctVariable = ctVariable;
	}

	public Date getFechPeriodo() {
		return this.fechPeriodo;
	}

	public void setFechPeriodo(Date fechPeriodo) {
		this.fechPeriodo = fechPeriodo;
	}

	public long getNumPeriodo() {
		return this.numPeriodo;
	}

	public void setNumPeriodo(long numPeriodo) {
		this.numPeriodo = numPeriodo;
	}

	public Double getValValor() {
		return this.valValor;
	}

	public void setValValor(Double valValor) {
		this.valValor = valValor;
	}

	public Long getIdVersion() {
		return this.idVersion;
	}

	public void setIdVersion(Long idVersion) {
		this.idVersion = idVersion;
	}

	public BigDecimal getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(BigDecimal idEstatus) {
		this.idEstatus = idEstatus;
	}

}
