package com.cgaf.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * HtCincambiental generated by hbm2java
 */
public class HtGeneric {

	private Integer idPee;
	private CtVariable ctVariable;
	private Date fechPeriodo;
	private Integer numPeriodo;
	private Double valValor;
	private Integer idVersion;
	private BigDecimal idEstatus;

	public HtGeneric() {
	}

	public HtGeneric(Integer idPee, CtVariable ctVariable,
			Date fechPeriodo, Integer numPeriodo) {
		this.idPee = idPee;
		this.ctVariable = ctVariable;
		this.fechPeriodo = fechPeriodo;
		this.numPeriodo = numPeriodo;
	}

	public HtGeneric(Integer idPee, CtVariable ctVariable,
			Date fechPeriodo, Integer numPeriodo, Double valValor, Integer idVersion,
			BigDecimal idEstatus) {
		this.idPee = idPee;
		this.ctVariable = ctVariable;
		this.fechPeriodo = fechPeriodo;
		this.numPeriodo = numPeriodo;
		this.valValor = valValor;
		this.idVersion = idVersion;
		this.idEstatus = idEstatus;
	}

	public Integer getIdPee() {
		return this.idPee;
	}

	public void setIdPee(Integer idPee) {
		this.idPee = idPee;
	}

	public CtVariable getCtVariable() {
		return this.ctVariable;
	}

	public void setCtVariable(CtVariable ctVariable) {
		this.ctVariable = ctVariable;
	}

	public Date getFechPeriodo() {
		return this.fechPeriodo;
	}

	public void setFechPeriodo(Date fechPeriodo) {
		this.fechPeriodo = fechPeriodo;
	}

	public Integer getNumPeriodo() {
		return this.numPeriodo;
	}

	public void setNumPeriodo(Integer numPeriodo) {
		this.numPeriodo = numPeriodo;
	}

	public Double getValValor() {
		return this.valValor;
	}

	public void setValValor(Double valValor) {
		this.valValor = valValor;
	}

	public Integer getIdVersion() {
		return this.idVersion;
	}

	public void setIdVersion(Integer idVersion) {
		this.idVersion = idVersion;
	}

	public BigDecimal getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(BigDecimal idEstatus) {
		this.idEstatus = idEstatus;
	}

}
