package com.cgaf.model;

// Generated 04-ago-2015 22:38:37 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

/**
 * LogImportacion generated by hbm2java
 */
public class LogImportacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idLog;
	private String nombreUsuario;
	private Date fechaProceso;
	private String nombreProceso;
	private Timestamp fechaInicio;
	private Timestamp fechaFin;
	private Integer regTransferidos;
	private String status;
	private String comentarios;

	public LogImportacion() {
	}

	public LogImportacion(Integer idLog) {
		this.idLog = idLog;
	}

	public LogImportacion(Integer idLog, String nombreUsuario,
			Date fechaProceso, String nombreProceso, Timestamp fechaInicio,
			Timestamp fechaFin, Integer regTransferidos, String status,
			String comentarios) {
		this.idLog = idLog;
		this.nombreUsuario = nombreUsuario;
		this.fechaProceso = fechaProceso;
		this.nombreProceso = nombreProceso;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.regTransferidos = regTransferidos;
		this.status = status;
		this.comentarios = comentarios;
	}

	public Integer getIdLog() {
		return this.idLog;
	}

	public void setIdLog(Integer idLog) {
		this.idLog = idLog;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public Date getFechaProceso() {
		return this.fechaProceso;
	}

	public void setFechaProceso(Date fechaProceso) {
		this.fechaProceso = fechaProceso;
	}

	public String getNombreProceso() {
		return this.nombreProceso;
	}

	public void setNombreProceso(String nombreProceso) {
		this.nombreProceso = nombreProceso;
	}

	public Timestamp getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Timestamp fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Timestamp getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Timestamp fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Integer getRegTransferidos() {
		return this.regTransferidos;
	}

	public void setRegTransferidos(Integer regTransferidos) {
		this.regTransferidos = regTransferidos;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

}
