package com.cgaf.model;

// Generated 12-jul-2015 21:00:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * MtPlantilla generated by hbm2java
 */
public class MtPlantilla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idPlantilla;
	private String idPee;
	private Byte idTipoplantilla;
	private String descPlantilla;
	private BigDecimal tipoLectura;
	private String descPlantillacorta;

	public MtPlantilla() {
	}

	public MtPlantilla(short idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public MtPlantilla(short idPlantilla, String idPee, Byte idTipoplantilla,
			String descPlantilla, BigDecimal tipoLectura,
			String descPlantillacorta) {
		this.idPlantilla = idPlantilla;
		this.idPee = idPee;
		this.idTipoplantilla = idTipoplantilla;
		this.descPlantilla = descPlantilla;
		this.tipoLectura = tipoLectura;
		this.descPlantillacorta = descPlantillacorta;
	}

	public short getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(short idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public String getIdPee() {
		return this.idPee;
	}

	public void setIdPee(String idPee) {
		this.idPee = idPee;
	}

	public Byte getIdTipoplantilla() {
		return this.idTipoplantilla;
	}

	public void setIdTipoplantilla(Byte idTipoplantilla) {
		this.idTipoplantilla = idTipoplantilla;
	}

	public String getDescPlantilla() {
		return this.descPlantilla;
	}

	public void setDescPlantilla(String descPlantilla) {
		this.descPlantilla = descPlantilla;
	}

	public BigDecimal getTipoLectura() {
		return this.tipoLectura;
	}

	public void setTipoLectura(BigDecimal tipoLectura) {
		this.tipoLectura = tipoLectura;
	}

	public String getDescPlantillacorta() {
		return this.descPlantillacorta;
	}

	public void setDescPlantillacorta(String descPlantillacorta) {
		this.descPlantillacorta = descPlantillacorta;
	}

}
