package com.cgaf.model;

// Generated 04-ago-2015 22:38:37 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * MtPlantilla generated by hbm2java
 */
public class MtPlantilla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPlantilla;
	private String idPee;
	private Timestamp idTipoplantilla;
	private String descPlantilla;
	private Timestamp tipoLectura;
	private String descPlantillacorta;

	public MtPlantilla() {
	}

	public MtPlantilla(Integer idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public MtPlantilla(Integer idPlantilla, String idPee, Timestamp idTipoplantilla,
			String descPlantilla, Timestamp tipoLectura,
			String descPlantillacorta) {
		this.idPlantilla = idPlantilla;
		this.idPee = idPee;
		this.idTipoplantilla = idTipoplantilla;
		this.descPlantilla = descPlantilla;
		this.tipoLectura = tipoLectura;
		this.descPlantillacorta = descPlantillacorta;
	}

	public Integer getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(Integer idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public String getIdPee() {
		return this.idPee;
	}

	public void setIdPee(String idPee) {
		this.idPee = idPee;
	}

	public Timestamp getIdTipoplantilla() {
		return this.idTipoplantilla;
	}

	public void setIdTipoplantilla(Timestamp idTipoplantilla) {
		this.idTipoplantilla = idTipoplantilla;
	}

	public String getDescPlantilla() {
		return this.descPlantilla;
	}

	public void setDescPlantilla(String descPlantilla) {
		this.descPlantilla = descPlantilla;
	}

	public Timestamp getTipoLectura() {
		return this.tipoLectura;
	}

	public void setTipoLectura(Timestamp tipoLectura) {
		this.tipoLectura = tipoLectura;
	}

	public String getDescPlantillacorta() {
		return this.descPlantillacorta;
	}

	public void setDescPlantillacorta(String descPlantillacorta) {
		this.descPlantillacorta = descPlantillacorta;
	}

}
